/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqltest2;

import java.awt.HeadlessException;
import java.awt.image.DataBufferUShort;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.*;

/**
 *
 * @author gunn
 */
public class editMenuFrame extends BasicVariable {
    Object[][] data;
    /**
     * Creates new form editMenuFrame
     */
    public editMenuFrame() {
        this.setTitle("Edit Menu");
        initComponents();
       DefaultTableModel model = new DefaultTableModel(new String[]{"MenuID", "MenuName", "Category","MenuCal","MenuCost"}, 0);
        data = new Object[20][5];
        
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Menu");
            ResultSetMetaData metaData = rs.getMetaData();
            int row = 0;
            while (rs.next()) {

                String d = rs.getString(1);
                String e = rs.getString(2);
                String f = rs.getString(3);
                String g = rs.getString(4);
                String h = rs.getString(5);
                model.addRow(new Object[]{d, e, f, g, h});
                jTable1.setModel(model);
            }
        }
        catch (Exception e){
            System.out.println(e.getCause());
            }
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertButton = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        MenuID_EL = new javax.swing.JLabel();
        MenuID_T = new javax.swing.JTextField();
        MenuName_EL = new javax.swing.JLabel();
        MenuName_T1 = new javax.swing.JTextField();
        Category_T = new javax.swing.JTextField();
        Category_EL = new javax.swing.JLabel();
        MenuCal_T = new javax.swing.JTextField();
        MenuCal_EL = new javax.swing.JLabel();
        MenuCost_T = new javax.swing.JTextField();
        MenuCost_EL = new javax.swing.JLabel();
        EDIT = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("EditMenu");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MenuID", "MenuName", "Category", "MenuCal", "MenuCost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("MenuID");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("MenuName");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Category");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("MenuCal");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("MenuCost");
        }

        InsertButton.setText("Insert Menu");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        MenuID_EL.setText("MENU_ID");

        MenuID_T.setEnabled(false);

        MenuName_EL.setText("MenuName");

        MenuName_T1.setEnabled(false);

        Category_T.setEnabled(false);

        Category_EL.setText("Category");

        MenuCal_T.setEnabled(false);

        MenuCal_EL.setText("MenuCal");

        MenuCost_T.setEnabled(false);

        MenuCost_EL.setText("MenuCost");

        EDIT.setText("EDIT");
        EDIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITMouseClicked(evt);
            }
        });
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.setEnabled(false);
        SAVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVEMouseClicked(evt);
            }
        });
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuID_EL)
                            .addComponent(MenuID_T, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenuName_EL)
                            .addComponent(MenuName_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Category_EL)
                            .addComponent(Category_T, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenuCal_EL)
                            .addComponent(MenuCal_T, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenuCost_EL)
                            .addComponent(MenuCost_T, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SAVE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(InsertButton)
                        .addGap(89, 89, 89)
                        .addComponent(DELETE)
                        .addGap(106, 106, 106)
                        .addComponent(EDIT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MenuID_EL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuID_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MenuName_EL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuName_T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Category_EL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Category_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MenuCal_EL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuCal_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MenuCost_EL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuCost_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SAVE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertButton)
                    .addComponent(DELETE)
                    .addComponent(EDIT))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        JFrame insert = new insertMenu();
        insert.setVisible(true);
        this.dispose();
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        
        try {
            int row = -1;
            Object id = null;
            try{
            row = jTable1.getSelectedRow();
            id =  jTable1.getModel().getValueAt(row, 0);
            ((DefaultTableModel)jTable1.getModel()).removeRow(row);
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(rootPane,"Error, Please Select 1 Row","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
            Statement scont = conn.createStatement(); 
            String q = "DELETE FROM Menu WHERE MenuID = "+id+"";
            scont.executeUpdate(q);
            } catch (SQLException ex) {
             System.err.println("Got an exception! "); 
            System.err.println(ex.getMessage()); 
        }
        
       
    }//GEN-LAST:event_DELETEActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDITActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void EDITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITMouseClicked
        // TODO add your handling code here:
        try {
            int row = -1;
            Object id = null;
            try{
                row = jTable1.getSelectedRow(); 
                id =  jTable1.getModel().getValueAt(row, 0);Category_T.setEnabled(true);
                MenuCal_T.setEnabled(true);
                MenuCost_T.setEnabled(true);
                MenuName_T1.setEnabled(true);
                SAVE.setEnabled(true);jTable1.setEnabled(false);
            }catch(ArrayIndexOutOfBoundsException exception){
               JOptionPane.showMessageDialog(rootPane,"Error, Please Select 1 Row","Error",JOptionPane.ERROR_MESSAGE);
            }
            Statement scont = conn.createStatement(); 
            ResultSet rss;
            rss = scont.executeQuery("SELECT* FROM Menu WHERE MenuID = "+id+"");
            //MenuID,MenuName,Category,MenuCal,MenuCost
         if(rss.next()){
             String menuid = rss.getString("MenuID");
             MenuID_T.setText(menuid);
             String menuName = rss.getString("MenuName");
             MenuName_T1.setText(menuName);
             String category = rss.getString("Category");
             Category_T.setText(category);
             String menuCal = rss.getString("MenuCal");
             MenuCal_T.setText(menuCal);
             String menuCost = rss.getString("MenuCost");
             MenuCost_T.setText(menuCost);
             
         }
               
 
        }
        catch (SQLException ex) {
            //Logger.getLogger(insertMenu.class.getName()).log(Level.SEVERE, null, ex);
             System.err.println("Got an exception! "); 
            System.err.println(ex.getMessage()); 
        }catch (HeadlessException e){
            System.out.println("System error please try again");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_EDITMouseClicked

    private void SAVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseClicked
        // TODO add your handling code here:
             String menuName = MenuName_T1.getText();
             String category = Category_T.getText();
              Object menuCal = null ,menuCost = null;
           
             if("".equals(MenuCal_T.getText())&&!("".equals(MenuCost_T.getText()))){    
                 menuCal = null;
                  menuCost = Integer.parseInt(MenuCost_T.getText());
             }
             else if( "".equals(MenuCost_T.getText())&&!("".equals(MenuCal_T.getText()))){
                 menuCost = null;
                 menuCal = Integer.parseInt(MenuCal_T.getText());
             }
             else if("".equals(MenuCal_T.getText())&&"".equals(MenuCost_T.getText())){
              menuCal = null ;
              menuCost = null;
             }else{
             menuCal = Integer.parseInt(MenuCal_T.getText());
             menuCost = Integer.parseInt(MenuCost_T.getText());
             }
             
           jTable1.setEnabled(true);
         try {
            int row = jTable1.getSelectedRow();
            Object id =  jTable1.getModel().getValueAt(row, 0);
            Statement scont = conn.createStatement(); 
            String q = "UPDATE Menu SET MenuName = '"+menuName+"',Category = '"+category+"',MenuCal = "+menuCal+",MenuCost = "+menuCost+" WHERE MenuID = "+id+"";
             ((DefaultTableModel)jTable1.getModel()).setValueAt(menuName, row, 1);
             ((DefaultTableModel)jTable1.getModel()).setValueAt(category, row, 2);
             ((DefaultTableModel)jTable1.getModel()).setValueAt(menuCal, row, 3);
             ((DefaultTableModel)jTable1.getModel()).setValueAt(menuCost, row, 4);
            scont.executeUpdate(q);
            Category_T.setEnabled(false);
        MenuCal_T.setEnabled(false);
        MenuCost_T.setEnabled(false);
        MenuName_T1.setEnabled(false);
        SAVE.setEnabled(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(insertMenu.class.getName()).log(Level.SEVERE, null, ex);
             System.err.println("Got an exception! "); 
            System.err.println(ex.getMessage()); 
        }
         
        
    }//GEN-LAST:event_SAVEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category_EL;
    private javax.swing.JTextField Category_T;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel MenuCal_EL;
    private javax.swing.JTextField MenuCal_T;
    private javax.swing.JLabel MenuCost_EL;
    private javax.swing.JTextField MenuCost_T;
    private javax.swing.JLabel MenuID_EL;
    private javax.swing.JTextField MenuID_T;
    private javax.swing.JLabel MenuName_EL;
    private javax.swing.JTextField MenuName_T1;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
