/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqltest2;

import java.sql.*;
import java.sql.Statement;
import java.text.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author AdMiN
 */
public class sellFrame extends BasicVariable {
    ResultSet rs;
    //store key to show in list table
    ArrayList<String> menuNametoShow = new ArrayList<>();
    ArrayList<String> menuIdtoShow = new ArrayList<>();
    String menuType;
    //store menu detail from sql
    ArrayList<String> menuList = new ArrayList<>();
    ArrayList<String> menuIdList = new ArrayList<>();
    
    DefaultListModel listModel = new DefaultListModel();
   
    /**
     * Creates new form MenuFrame
     */
    public sellFrame() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
       
        this.setTitle(dateFormat.format(date));
        

//set disable menu button
        FoodBtn1.setEnabled(false);
        FoodBtn2.setEnabled(false);
        FoodBtn3.setEnabled(false);
        FoodBtn4.setEnabled(false);
        FoodBtn5.setEnabled(false);
    }
    private void setDetailMenuArrayAndFoodBtn(){
        menuList = new ArrayList<>();
        menuIdList = new ArrayList<>();
        try {
            Statement st = conn.createStatement();
            rs = st.executeQuery("SELECT MenuName FROM Menu WHERE Category ='" + menuType + "'");
            while (rs.next()) {
                menuList.add(rs.getString(1));
            }
            rs = st.executeQuery("SELECT MenuId FROM Menu WHERE Category ='" + menuType + "'");
            while (rs.next()) {
                menuIdList.add(rs.getString(1));
            }
          

        } catch (Exception e) {
            System.out.println(e);
        }
        int i = 0;
        if (menuList.size() > 0) {
            FoodBtn1.setText(menuList.get(0));
            i++;
        }
        if (menuList.size() > 1) {
            FoodBtn2.setText(menuList.get(1));
            i++;
        }
        if (menuList.size() > 2) {
            FoodBtn3.setText(menuList.get(2));
            i++;
        }
        if (menuList.size() > 3) {
            FoodBtn4.setText(menuList.get(3));
            i++;
        }
        if (menuList.size() > 4) {
            FoodBtn5.setText(menuList.get(4));
            i++;
        }
        if (menuList.size() > 5) {
            FoodBtn5.setText(menuList.get(5));
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MeatButton = new javax.swing.JButton();
        VetButton = new javax.swing.JButton();
        RiceButton = new javax.swing.JButton();
        ExtraButton = new javax.swing.JButton();
        FoodBtn1 = new javax.swing.JButton();
        FoodBtn2 = new javax.swing.JButton();
        FoodBtn3 = new javax.swing.JButton();
        FoodBtn4 = new javax.swing.JButton();
        FoodBtn5 = new javax.swing.JButton();
        SelectTableBtn = new javax.swing.JButton();
        insertTableBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        MenuListTable = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MeatButton.setText("Meat");
        MeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeatButtonActionPerformed(evt);
            }
        });

        VetButton.setText("Vetgetable");
        VetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VetButtonActionPerformed(evt);
            }
        });

        RiceButton.setText("Rice");
        RiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiceButtonActionPerformed(evt);
            }
        });

        ExtraButton.setText("Extra");
        ExtraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraButtonActionPerformed(evt);
            }
        });

        FoodBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtn1ActionPerformed(evt);
            }
        });

        FoodBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtn2ActionPerformed(evt);
            }
        });

        FoodBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtn5ActionPerformed(evt);
            }
        });

        SelectTableBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SelectTableBtn.setText("เลือกโต๊ะ");

        insertTableBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insertTableBtn.setText("เพิ่มโต๊ะ");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("สั่งอาหาร");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        confirmBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirmBtn.setText("ยืนยัน");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("จ่ายเงิน");

        label1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("TableNo.");

        label2.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("เลขอะไรก็ว่าไป");

        MenuListTable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "MenuList" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(MenuListTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FoodBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FoodBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FoodBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MeatButton)
                        .addGap(34, 34, 34)
                        .addComponent(VetButton)
                        .addGap(22, 22, 22)
                        .addComponent(RiceButton)
                        .addGap(26, 26, 26)
                        .addComponent(ExtraButton))
                    .addComponent(FoodBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(confirmBtn))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(SelectTableBtn)
                                .addGap(18, 51, Short.MAX_VALUE)
                                .addComponent(insertTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FoodBtn1, FoodBtn2, FoodBtn3, FoodBtn4, FoodBtn5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExtraButton, MeatButton, RiceButton, VetButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SelectTableBtn, confirmBtn, insertTableBtn, jButton3, jButton5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MeatButton)
                            .addComponent(VetButton)
                            .addComponent(RiceButton)
                            .addComponent(ExtraButton))
                        .addGap(32, 32, 32)
                        .addComponent(FoodBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FoodBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FoodBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FoodBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(FoodBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertTableBtn)
                    .addComponent(SelectTableBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FoodBtn1, FoodBtn2, FoodBtn3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeatButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        
        menuType="Meat";
        
        setDetailMenuArrayAndFoodBtn();

// TODO add your handling code here:
    }//GEN-LAST:event_MeatButtonActionPerformed

    private void FoodBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodBtn5ActionPerformed

    private void VetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VetButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        
        menuType="Vet";
        
        setDetailMenuArrayAndFoodBtn();

        // TODO add your handling code here:
    }//GEN-LAST:event_VetButtonActionPerformed

    private void RiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiceButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        
        menuType="Rice";
        
       setDetailMenuArrayAndFoodBtn();        
// TODO add your handling code here:
    }//GEN-LAST:event_RiceButtonActionPerformed

    private void ExtraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraButtonActionPerformed
        FoodBtn1.setText(null);
        FoodBtn2.setText(null);
        FoodBtn3.setText(null);
        FoodBtn4.setText(null);
        FoodBtn5.setText(null);
        
        menuType="Extra";
        
       setDetailMenuArrayAndFoodBtn();
// TODO add your handling code here:
    }//GEN-LAST:event_ExtraButtonActionPerformed

    private void FoodBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtn2ActionPerformed
        menuNametoShow.add(menuList.get(1));
        menuIdtoShow.add(menuIdList.get(1));
        try {
            

            listModel.addElement(menuList.get(1));
            MenuListTable.setModel(listModel);

    }                                        
        
        catch (Exception e) {
                    System.out.println(e);
                }
                   // TODO add your handling code here:
    }//GEN-LAST:event_FoodBtn2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FoodBtn1.setEnabled(true);
        FoodBtn2.setEnabled(true);
        FoodBtn3.setEnabled(true);
        FoodBtn4.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FoodBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtn1ActionPerformed

        menuNametoShow.add(menuList.get(0));
        menuIdtoShow.add(menuIdList.get(0));
        try {
            

            listModel.addElement(menuList.get(0));
            MenuListTable.setModel(listModel);

    }//GEN-LAST:event_FoodBtn1ActionPerformed
        
        catch (Exception e) {
                    System.out.println(e);
                }
            }
    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExtraButton;
    private javax.swing.JButton FoodBtn1;
    private javax.swing.JButton FoodBtn2;
    private javax.swing.JButton FoodBtn3;
    private javax.swing.JButton FoodBtn4;
    private javax.swing.JButton FoodBtn5;
    private javax.swing.JButton MeatButton;
    private javax.swing.JList<String> MenuListTable;
    private javax.swing.JButton RiceButton;
    private javax.swing.JButton SelectTableBtn;
    private javax.swing.JButton VetButton;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton insertTableBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
